### ISSUE TITLE
question to the new feature vertxEventBusProvider.disableAutoConnect()

### ISSUE THREAD

**Issue by TeilZeitMensch** [knalli/angular-vertxbus#90]
Hi, 

i am already using the new feature vertxEventBusProvider.disableAutoConnect().

In my Application, i then use:
vertxEventBus.configureConnection(serverAddress, '/eventbus').connect() , and this works fine.

But i am wondering, wether i should have a kind of callback or something else, when the connection is finished.

Could it be a good feature, to make .connect() a promise, so that i could use: 
vertxEventBus.configureConnection(serverAddress, '/eventbus').connect().then(function() {
...
}
or is this an unnecessary feature, cause i overlook something?

Thanks in advance

**Comment by knalli** [comment]
Yes, it would be a good addition to return a promise which will be resolved in the onopen callback made in connect().

Do you like to make a PR?

**Comment by leolux** [comment]
Why not using the standard event "eventbus.system.connected" for this?

**Comment by knalli** [comment]
@leolux 2 reasons: a) The event is part of the service, but not the wrapper/adapter. I'm definitely  against a dependency adapter -> service: bad design and even a stunt because it will result into cross dependencies. b) Even if the `connect()` would fire this event: The scope [here](https://github.com/knalli/angular-vertxbus/blob/d9406cff7e6faf32ee17d79a8ae367ee440418c8/src/lib/adapter/EventBusAdapter.js#L132-L173) is well defined. ;)
